---
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  ecmaVersion: 2022
  sourceType: 'module'
rules:
  id-length:
    - 0
  no-param-reassign:
    - 0
  consistent-return:
    - 0
  no-console:
    - 0
extends: airbnb-base
plugins: [ import ]
